<?php
declare(strict_types=1);

/**
 * เนื้อหาเว็บไซต์ — แก้จำนวนที่นั่ง/กระเป๋า/ราคาได้จากไฟล์นี้
 * ห้ามใส่ราคาปลอม / รีวิวปลอม / ตัวเลขเคลมที่ไม่มีหลักฐาน
 */

return [
    'vehicles' => [
        [
            'id' => 'sedan',
            'name' => 'รถเก๋ง',
            'passengers' => '1–4 คน',
            'passengers_min' => 1,
            'passengers_max' => 4,
            'luggage' => '2–3 ใบ',
            'suitable' => 'คู่รักและครอบครัวขนาดเล็ก',
            'description' => 'เหมาะกับทริปในเมือง รับส่งสนามบิน และเส้นทางที่ไม่ต้องการพื้นที่สัมภาระมาก',
            'price_label' => 'สอบถามราคา',
            'price' => null,
            'image' => 'vehicles/chiangmai-sedan-with-driver',
            'alt' => 'รถเก๋งพร้อมคนขับเชียงใหม่',
            'url' => '/vehicles/sedan/',
            'future_url' => '/vehicles/sedan/',
        ],
        [
            'id' => 'suv',
            'name' => 'SUV',
            'passengers' => '1–6 คน',
            'passengers_min' => 1,
            'passengers_max' => 6,
            'luggage' => '3–4 ใบ',
            'suitable' => 'ครอบครัวและเส้นทางที่ต้องการพื้นที่สัมภาระมากขึ้น',
            'description' => 'เหมาะกับทริปขึ้นดอย เดินทางหลายจุด และครอบครัวที่ต้องการความคล่องตัว',
            'price_label' => 'สอบถามราคา',
            'price' => null,
            'image' => 'vehicles/chiangmai-suv-with-driver',
            'alt' => 'SUV พร้อมคนขับเชียงใหม่',
            'url' => '/vehicles/suv/',
            'future_url' => '/vehicles/suv/',
        ],
        [
            'id' => 'van',
            'name' => 'รถตู้',
            'passengers' => '1–10 คน',
            'passengers_min' => 1,
            'passengers_max' => 10,
            'luggage' => '6–8 ใบ',
            'suitable' => 'กลุ่มเพื่อน ครอบครัวใหญ่ และการเดินทางเป็นกลุ่ม',
            'description' => 'เหมาะกับทริปกลุ่ม เหมาเที่ยว และเดินทางต่างจังหวัดที่ต้องการพื้นที่นั่งสบาย',
            'price_label' => 'สอบถามราคา',
            'price' => null,
            'image' => 'vehicles/chiangmai-van-with-driver',
            'alt' => 'รถตู้พร้อมคนขับเชียงใหม่',
            'url' => '/vehicles/van/',
            'future_url' => '/vehicles/van/',
        ],
    ],

    'services' => [
        [
            'id' => 'airport',
            'title' => 'รถรับส่งสนามบินเชียงใหม่',
            'description' => 'สำหรับเดินทางจากสนามบินไปโรงแรม ที่พัก หรือจุดหมายต่าง ๆ',
            'url' => '/airport-transfer-chiangmai/',
            'future_url' => '/airport-transfer-chiangmai/',
        ],
        [
            'id' => 'city-tour',
            'title' => 'เหมารถเที่ยวเชียงใหม่',
            'description' => 'เหมาะสำหรับทริปครึ่งวัน เต็มวัน และหลายวัน',
            'url' => '/car-with-driver-chiangmai/',
            'future_url' => '/car-with-driver-chiangmai/',
        ],
        [
            'id' => 'sedan',
            'title' => 'รถเก๋งพร้อมคนขับ',
            'description' => 'เหมาะกับคู่รักและครอบครัวขนาดเล็ก',
            'url' => '/vehicles/sedan/',
            'future_url' => '/vehicles/sedan/',
        ],
        [
            'id' => 'suv',
            'title' => 'SUV พร้อมคนขับ',
            'description' => 'เหมาะกับครอบครัวและเส้นทางที่ต้องการพื้นที่สัมภาระมากขึ้น',
            'url' => '/vehicles/suv/',
            'future_url' => '/vehicles/suv/',
        ],
        [
            'id' => 'van',
            'title' => 'รถตู้พร้อมคนขับ',
            'description' => 'เหมาะสำหรับกลุ่มเพื่อน ครอบครัวใหญ่ และการเดินทางเป็นกลุ่ม',
            'url' => '/vehicles/van/',
            'future_url' => '/vehicles/van/',
        ],
        [
            'id' => 'interprovincial',
            'title' => 'เดินทางต่างจังหวัด',
            'description' => 'เชียงราย ปาย ลำปาง ลำพูน และพื้นที่ภาคเหนือ',
            'url' => '/car-with-driver-chiangmai/',
            'future_url' => '/car-with-driver-chiangmai/',
        ],
    ],

    'destinations' => [
        [
            'id' => 'mae-kampong',
            'name' => 'แม่กำปอง',
            'keyword' => 'รถไปแม่กำปองจากเชียงใหม่',
            'description' => 'หมู่บ้านบนดอย อากาศเย็น เหมาะกับทริปวันเดียวหรือค้างคืน',
            'duration' => 'ประมาณ 1.5 ชม.',
            'recommended_vehicle' => 'รถเก๋ง / SUV / รถตู้',
            'image' => 'destinations/mae-kampong-private-car',
            'alt' => 'รถพร้อมคนขับเชียงใหม่สำหรับเที่ยวแม่กำปอง',
            'url' => '/destinations/mae-kampong/',
            'future_url' => '/destinations/mae-kampong/',
        ],
        [
            'id' => 'mon-jam',
            'name' => 'ม่อนแจ่ม',
            'keyword' => 'รถไปม่อนแจ่ม',
            'description' => 'ทุ่งดอกไม้ วิวภูเขา และอากาศเย็นใกล้ตัวเมือง',
            'duration' => 'ประมาณ 1 ชม.',
            'recommended_vehicle' => 'รถเก๋ง / SUV / รถตู้',
            'image' => 'destinations/mon-jam-car-with-driver',
            'alt' => 'รถพร้อมคนขับไปม่อนแจ่มจากเชียงใหม่',
            'url' => '/destinations/mon-jam/',
            'future_url' => '/destinations/mon-jam/',
        ],
        [
            'id' => 'doi-inthanon',
            'name' => 'ดอยอินทนนท์',
            'keyword' => 'รถไปดอยอินทนนท์พร้อมคนขับ',
            'description' => 'จุดสูงสุดของไทย เหมาะกับทริปเต็มวันพร้อมจุดแวะชมวิว',
            'duration' => 'ประมาณ 2 ชม.',
            'recommended_vehicle' => 'รถเก๋ง / SUV / รถตู้',
            'image' => 'destinations/doi-inthanon-car-with-driver',
            'alt' => 'รถไปดอยอินทนนท์พร้อมคนขับจากเชียงใหม่',
            'url' => '/destinations/doi-inthanon/',
            'future_url' => '/destinations/doi-inthanon/',
        ],
        [
            'id' => 'doi-suthep',
            'name' => 'ดอยสุเทพ',
            'keyword' => 'รถเที่ยวดอยสุเทพ',
            'description' => 'วัดและวิวเมืองเชียงใหม่ เหมาะกับทริปเช้าหรือครึ่งวัน',
            'duration' => 'ประมาณ 45 นาที',
            'recommended_vehicle' => 'รถเก๋ง / SUV / รถตู้',
            'image' => 'destinations/doi-suthep-car-with-driver',
            'alt' => 'รถเที่ยวดอยสุเทพพร้อมคนขับ',
            'url' => '/destinations/doi-suthep/',
            'future_url' => '/destinations/doi-suthep/',
        ],
        [
            'id' => 'chiang-dao',
            'name' => 'เชียงดาว',
            'keyword' => 'รถเชียงใหม่ไปเชียงดาว',
            'description' => 'ทริปธรรมชาติและอากาศเย็น เหมาะวันเดียวหรือค้างคืน',
            'duration' => 'ประมาณ 1.5–2 ชม.',
            'recommended_vehicle' => 'รถเก๋ง / SUV / รถตู้',
            'image' => 'destinations/chiang-dao-car-with-driver',
            'alt' => 'รถเชียงใหม่ไปเชียงดาวพร้อมคนขับ',
            'url' => '/destinations/chiang-dao/',
            'future_url' => '/destinations/chiang-dao/',
        ],
        [
            'id' => 'chiang-rai',
            'name' => 'เชียงราย',
            'keyword' => 'รถเชียงใหม่ไปเชียงราย',
            'description' => 'เดินทางต่างจังหวัด แวะจุดท่องเที่ยวตามแผนที่ต้องการ',
            'duration' => 'ประมาณ 3 ชม.',
            'recommended_vehicle' => 'รถเก๋ง / SUV / รถตู้',
            'image' => 'destinations/chiang-rai-car-with-driver',
            'alt' => 'รถเชียงใหม่ไปเชียงรายพร้อมคนขับ',
            'url' => '/destinations/chiang-rai/',
            'future_url' => '/destinations/chiang-rai/',
        ],
        [
            'id' => 'pai',
            'name' => 'ปาย',
            'keyword' => 'รถเชียงใหม่ไปปาย',
            'description' => 'เส้นทางเขาโค้ง แนะนำให้มีคนขับชำนาญทางพาไป',
            'duration' => 'ประมาณ 3.5 ชม.',
            'recommended_vehicle' => 'รถเก๋ง / SUV / รถตู้',
            'image' => 'destinations/pai-car-with-driver',
            'alt' => 'รถเชียงใหม่ไปปายพร้อมคนขับ',
            'url' => '/destinations/pai/',
            'future_url' => '/destinations/pai/',
        ],
        [
            'id' => 'ang-khang',
            'name' => 'อ่างขาง',
            'keyword' => 'รถเชียงใหม่ไปอ่างขาง',
            'description' => 'ดอยอ่างขาง อากาศเย็น ชมสวนและวิวดอย เหมาะทริปวันเดียวหรือค้างคืน',
            'duration' => 'ประมาณ 2.5–3 ชม.',
            'recommended_vehicle' => 'รถเก๋ง / SUV / รถตู้',
            'image' => 'destinations/ang-khang-car-with-driver',
            'alt' => 'รถเชียงใหม่ไปอ่างขางพร้อมคนขับ',
            'url' => '/destinations/ang-khang/',
            'future_url' => '/destinations/ang-khang/',
        ],
        [
            'id' => 'pa-bong-piang',
            'name' => 'ป่าบงเปียง',
            'keyword' => 'รถเชียงใหม่ไปป่าบงเปียง',
            'description' => 'ทุ่งนาขั้นบันไดและวิวภูเขา เหมาะทริปชมวิวและถ่ายรูป',
            'duration' => 'ประมาณ 2–2.5 ชม.',
            'recommended_vehicle' => 'รถเก๋ง / SUV / รถตู้',
            'image' => 'destinations/pa-bong-piang-car-with-driver',
            'alt' => 'รถเชียงใหม่ไปป่าบงเปียงพร้อมคนขับ',
            'url' => '/destinations/pa-bong-piang/',
            'future_url' => '/destinations/pa-bong-piang/',
        ],
        [
            'id' => 'nine-temples',
            'name' => 'ไหว้พระ 9 วัด',
            'keyword' => 'ทริปไหว้พระ 9 วัดเชียงใหม่',
            'description' => 'ทริปทำบุญรอบเมือง ปรับจุดแวะวัดได้ตามแผน',
            'duration' => 'ทริปวันเดียว',
            'recommended_vehicle' => 'รถเก๋ง / SUV / รถตู้',
            'image' => 'destinations/doi-suthep-car-with-driver',
            'alt' => 'ทริปไหว้พระ 9 วัดเชียงใหม่พร้อมคนขับ',
            'url' => '/destinations/nine-temples/',
            'future_url' => '/destinations/nine-temples/',
        ],
        [
            'id' => 'doi-suthep-mon-jam',
            'name' => 'ดอยสุเทพ–ม่อนแจ่ม',
            'keyword' => 'รถเที่ยวดอยสุเทพม่อนแจ่ม',
            'description' => 'รวมสองจุดยอดนิยมในวันเดียว พร้อมคาเฟ่และวิวเขา',
            'duration' => 'ทริปวันเดียว',
            'recommended_vehicle' => 'รถเก๋ง / SUV / รถตู้',
            'image' => 'destinations/mon-jam-car-with-driver',
            'alt' => 'รถเที่ยวดอยสุเทพและม่อนแจ่มพร้อมคนขับ',
            'url' => '/destinations/doi-suthep-mon-jam/',
            'future_url' => '/destinations/doi-suthep-mon-jam/',
        ],
        [
            'id' => 'pang-hai',
            'name' => 'ปางไฮ (เทพเสด็จ)',
            'keyword' => 'รถไปปางไฮเทพเสด็จ',
            'description' => 'น้ำตกเทพเสด็จและคาเฟ่บนดอย เหมาะทริปชิลล์',
            'duration' => 'ทริปวันเดียว',
            'recommended_vehicle' => 'รถเก๋ง / SUV / รถตู้',
            'image' => 'destinations/mon-jam-car-with-driver',
            'alt' => 'รถไปปางไฮเทพเสด็จพร้อมคนขับ',
            'url' => '/destinations/pang-hai/',
            'future_url' => '/destinations/pang-hai/',
        ],
        [
            'id' => 'chiang-rai-long',
            'name' => 'เชียงราย (ยาว)',
            'keyword' => 'ทริปเชียงรายยาวพร้อมคนขับ',
            'description' => 'ทริปยาวรวมแม่สายและจุดสำคัญในเชียงราย',
            'duration' => 'ประมาณ 12 ชม.',
            'recommended_vehicle' => 'รถเก๋ง / SUV / รถตู้',
            'image' => 'destinations/chiang-rai-car-with-driver',
            'alt' => 'ทริปเชียงรายยาวพร้อมคนขับ',
            'url' => '/destinations/chiang-rai-long/',
            'future_url' => '/destinations/chiang-rai-long/',
        ],
        [
            'id' => 'hinoki-land',
            'name' => 'ฮิโนกิแลนด์',
            'keyword' => 'รถไปฮิโนกิแลนด์พร้อมคนขับ',
            'description' => 'ฮิโนกิแลนด์ ถ้ำเชียงดาว และวัดบ้านเด่นในวันเดียว',
            'duration' => 'ทริปวันเดียว',
            'recommended_vehicle' => 'รถเก๋ง / SUV / รถตู้',
            'image' => 'destinations/chiang-dao-car-with-driver',
            'alt' => 'รถไปฮิโนกิแลนด์พร้อมคนขับ',
            'url' => '/destinations/hinoki-land/',
            'future_url' => '/destinations/hinoki-land/',
        ],
        [
            'id' => 'pai-pang-ung',
            'name' => 'ปาย–ปางอุ๋ง–รักไทย',
            'keyword' => 'ทริปปายปางอุ๋งรักไทย',
            'description' => 'ทริปหลายวัน ปาย ปางอุ๋ง และหมู่บ้านรักไทย',
            'duration' => 'หลายวัน · 2 คืน',
            'recommended_vehicle' => 'รถเก๋ง / SUV / รถตู้',
            'image' => 'destinations/pai-car-with-driver',
            'alt' => 'ทริปปายปางอุ๋งรักไทยพร้อมคนขับ',
            'url' => '/destinations/pai-pang-ung/',
            'future_url' => '/destinations/pai-pang-ung/',
        ],
    ],

    'trust_items' => [
        'รถพร้อมคนขับ',
        'เลือกเส้นทางได้',
        'รับส่งสนามบิน',
        'เที่ยววันเดียว / หลายวัน',
        'เช็กคิวก่อนจอง',
    ],

    'why_us' => [
        'เลือกรถตามจำนวนผู้โดยสาร',
        'วางแผนเส้นทางร่วมกับลูกค้า',
        'รับส่งสนามบินเชียงใหม่',
        'รองรับทริปวันเดียวและหลายวัน',
        'แจ้งรายละเอียดก่อนเดินทาง',
        'ติดต่อสะดวก',
        'เช็กคิวก่อนยืนยัน',
    ],

    'booking_steps' => [
        ['step' => '01', 'title' => 'แจ้งวันเดินทาง', 'desc' => 'บอกวันที่ต้องการใช้รถ'],
        ['step' => '02', 'title' => 'แจ้งเส้นทางและจำนวนผู้โดยสาร', 'desc' => 'ระบุจุดรับ จุดหมาย และจำนวนคน'],
        ['step' => '03', 'title' => 'รับรายละเอียดรถและราคา', 'desc' => 'เจ้าหน้าที่สรุปรถที่เหมาะและยอดให้พิจารณา'],
        ['step' => '04', 'title' => 'ยืนยันคิวและเดินทาง', 'desc' => 'ยืนยันคิวแล้วเตรียมตัวเดินทางได้เลย'],
    ],

    // reviews: ว่าง = ซ่อน section ใน production
    'reviews' => [],

    'faq' => [
        [
            'q' => 'รถเช่าพร้อมคนขับเชียงใหม่ราคาเท่าไร?',
            'a' => 'ราคาขึ้นกับประเภทรถ ระยะทาง จำนวนวัน และรูปแบบทริป กรุณาเช็กคิวเพื่อรับราคาตามแผนการเดินทางของคุณ',
        ],
        [
            'q' => 'ราคาเช่ารถรวมค่าคนขับหรือไม่?',
            'a' => 'บริการนี้เป็นรถพร้อมคนขับ โดยรายละเอียดที่รวมอยู่ในราคาจะแจ้งชัดเจนตอนยืนยันคิว',
        ],
        [
            'q' => 'ราคานี้รวมค่าน้ำมันหรือไม่?',
            'a' => 'เงื่อนไขค่าใช้จ่ายจะสรุปให้ก่อนยืนยันคิวทุกครั้ง เพื่อให้คุณตัดสินใจได้ชัดเจน',
        ],
        [
            'q' => 'มีรถรับส่งสนามบินเชียงใหม่หรือไม่?',
            'a' => 'มีบริการรถรับส่งสนามบินเชียงใหม่ไปยังโรงแรม ที่พัก หรือจุดหมายที่ระบุ',
        ],
        [
            'q' => 'ต้องจองรถล่วงหน้ากี่วัน?',
            'a' => 'แนะนำให้เช็กคิวล่วงหน้า โดยเฉพาะช่วงวันหยุดและเส้นทางยอดนิยม เพื่อให้จัดรถได้ตรงความต้องการ',
        ],
        [
            'q' => 'รถเก๋งรองรับผู้โดยสารกี่คน?',
            'a' => 'รถเก๋งรองรับประมาณ 1–4 คน (จำนวนที่นั่งสามารถอัปเดตได้ตามรถจริงในระบบ)',
        ],
        [
            'q' => 'รถตู้รองรับผู้โดยสารกี่คน?',
            'a' => 'รถตู้รองรับประมาณ 1–10 คน เหมาะกับกลุ่มเพื่อนและครอบครัวใหญ่',
        ],
        [
            'q' => 'สามารถไปแม่กำปองแบบวันเดียวได้หรือไม่?',
            'a' => 'ได้ สามารถวางแผนทริปวันเดียวไปแม่กำปองได้ โดยแจ้งจุดแวะและเวลาที่ต้องการตอนเช็กคิว',
        ],
        [
            'q' => 'สามารถเหมารถไปดอยอินทนนท์ได้หรือไม่?',
            'a' => 'ได้ มีบริการเหมารถพร้อมคนขับไปดอยอินทนนท์ ทั้งแบบวันเดียวและตามแผนที่ตกลงกัน',
        ],
        [
            'q' => 'มีรถเชียงใหม่ไปเชียงรายหรือไม่?',
            'a' => 'มีบริการรถเชียงใหม่ไปเชียงรายพร้อมคนขับ และสามารถวางจุดแวะระหว่างทางได้',
        ],
        [
            'q' => 'มีรถเชียงใหม่ไปปายหรือไม่?',
            'a' => 'มีบริการรถเชียงใหม่ไปปายพร้อมคนขับ แนะนำให้เช็กคิวล่วงหน้าเพื่อจัดรถที่เหมาะกับเส้นทางเขา',
        ],
        [
            'q' => 'สามารถเปลี่ยนเส้นทางระหว่างวันได้หรือไม่?',
            'a' => 'สามารถพูดคุยปรับแผนได้ตามความเหมาะสมและเวลาที่เหลือ โดยแจ้งคนขับ/เจ้าหน้าที่ระหว่างการใช้บริการ',
        ],
        [
            'q' => 'เดินทางหลายวันได้หรือไม่?',
            'a' => 'รองรับทั้งทริปวันเดียวและหลายวัน แจ้งจำนวนวันและเส้นทางตอนเช็กคิวได้เลย',
        ],
        [
            'q' => 'มีค่าใช้จ่ายกรณีเกินเวลาหรือไม่?',
            'a' => 'หากมีการใช้รถเกินเวลาที่ตกลง เงื่อนไขจะแจ้งให้ทราบก่อนยืนยันคิว',
        ],
    ],

    'nav' => [
        ['label' => 'หน้าแรก', 'href' => '/'],
        ['label' => 'บริการ', 'href' => '/car-with-driver-chiangmai/'],
        ['label' => 'ราคา', 'href' => '/price/'],
        ['label' => 'เส้นทาง', 'href' => '/#destinations'],
        ['label' => 'รีวิว', 'href' => '/reviews/'],
        ['label' => 'FAQ', 'href' => '/faq/'],
        ['label' => 'ติดต่อ', 'href' => '/contact/'],
    ],

    'future_pages' => [
        'car_with_driver' => '/car-with-driver-chiangmai/',
        'price' => '/price/',
        'airport' => '/airport-transfer-chiangmai/',
        'reviews' => '/reviews/',
        'about' => '/about/',
        'contact' => '/contact/',
        'faq' => '/faq/',
        'sedan' => '/vehicles/sedan/',
        'suv' => '/vehicles/suv/',
        'doi_suthep' => '/destinations/doi-suthep/',
        'chiang_dao' => '/destinations/chiang-dao/',
    ],
];
